### ISSUE TITLE
MORNING SESSION GROUP CODE REVIEW 

### ISSUE THREAD

**Issue by billionsjoel** [omarsalem7/Portfolio#5]
- Good use of the `background-position-y` property for alignment.
- I suggest you avoid using <br /> for purposes of responsive design, instead use the right CSS property to do that.
- Professional class naming is great
- I suggest you use a dynamic unit when dealing with values for font-size measurements to help with responsiveness. 
- Everything seems perfect for me. Good code.
-Try as much as possible to design your code to match the template provided.

**Comment by omarsalem7** [comment]
Done 😉
